cards:
  supplier:
    - title: אף פעם לא עבדנו עם גורמים בממשלה
      cards:
        -
          title: איך האתר הזה יעזור לי?
          icon: supp-a1
          text: |
                מעט מאוד עסקים משתתפים בהתקשרויות עם הממשלה. "רכש פתוח" יקל עליכם את תהליך ההיכרות, המעקב אחר פעילות הרכש הממשלתית ושיתוף עם אחרים.
          action:
            text: עוד על תהליכי הרכש
            target: modal:procure_processes
        -
          title: איך זה עובד בדיוק?
          icon: supp-a2
          text: |
                 אנחנו אוספים ומאחדים מידע ממקורות ממשלתיים שונים, כדי שתוכלו לצפות, לעקוב ולהבין כיצד הממשלה רוכשת שירותים ומוצרים בתחום שלכם. תוכלו גם להרשם לעדכונים שוטפים בנושאים רלוונטיים.
          action:
            text: עוד על מקורות המידע
            target: modal:data_sources
        -
          title: איך מתחילים?
          icon: supp-a3
          text: |
            חפשו נושא, שירות או מוצר. ניתן גם להזין במסך החיפוש שמות של עסקים דומים כדי לצפות בהתקשרויות עבר והווה שלהם עם גופי ממשל ולאחר מכן להירשם לקבלת עדכונים שוטפים.
          action:
            text: לחיפוש
            target: search

    - title: אנחנו כבר מספקים סחורה / שירותים לממשלה
      cards:
        -
          title: איך אוכל להישאר בעניינים?
          icon: supp-b1
          text: |
                 פשוט מאוד: במסך תוצאות החיפוש לוחצים על הכוכב שבשורת החיפוש. מעכשיו, תקבלו עדכונים שבועיים בנושאים שמעניינים אתכם. (דורש התחברות עם חשבון גוגל).
          action:
            text: למסך החיפושים השמורים שלכם
            target: href:/p/
        -
          title: איך ללמוד עוד על רכש בתחום או נושא?
          icon: supp-b2
          text: |
                בכל אחד ממסכי תהליכי הרכש וההתקשרויות תמצאו טבלת שאילתות חכמה, שתאפשר לכם לחקור עוד למצוא מידע רלוונטי נוסף.
          action:
            text: לדוגמה
            target: href:/i/tenders/office/516787/4-2010?li=11&theme=govbuy#questions
        -
          title: מצאתי משהו מעניין, מה עושים?
          icon: supp-b3
          text: |
            מצאת מכרז או התקשרות מעניינים? תמיד אפשר וכדאי לקרוא או לשתף עם אחרים ולהתייעץ. חוצמיזה, במידה וישנן פעולות שניתן לנקוט במסגרת הליך הרכש שמצאת נציג לך רעיונות לכיווני פעולה אפשריים.
          action:
            text: ספרו לי עוד
            target: modal:actions_to_take
  gov:
    - title: פעם ראשונה ב״רכש פתוח״
      cards:
        -
          title: מה אפשר לגלות כאן?
          icon: gov-a1
          text: |
                האתר יסייע לכם להכיר ולעקוב אחרי פעולות רכש והתקשרויות ממשלתיות בהווה ובעבר. תוכלו ללמוד על ספקים רלוונטיים, ליצור קשר עם אנשי קשר רלוונטיים בממשלה או לשתף עם חברים לעבודה.
          action:
            text: לחיפוש
            target: search
        -
          title: איך זה עובד בדיוק?
          icon: gov-a2
          text: |
                 אנחנו אוספים ומאחדים מידע ממקורות ממשלתיים שונים, כדי שתוכלו לצפות, לעקוב ולהבין כיצד הממשלה רוכשת שירותים ומוצרים בתחום שלכם. תוכלו גם להרשם לעדכונים שוטפים בנושאים רלוונטיים.
          action:
            text: עוד על מקורות המידע
            target: modal:data_sources
        -
          title: איך אוכל להישאר בעניינים?
          icon: gov-a3
          text: |
                 פשוט מאוד: במסך תוצאות החיפוש לוחצים על הכוכב שבשורת החיפוש. מעכשיו, תקבלו עדכונים שבועיים בנושאים שמעניינים אתכם. (דורש התחברות עם חשבון גוגל).
          action:
            text: לחיפוש ושמירה
            target: href:/p/

    - title: חזרתי, מה חדש?
      cards:
        -
          title: איך למצוא ספקים פוטנציאלים?
          icon: gov-b1
          text: |
            הזינו את שם המוצר, השירות או הספק שמעניין אתכם בחלון החיפוש.
          action:
            text: לחיפוש
            target: search
        -
          title: מה השתנה בתחומים שמעניינים אותי?
          icon: gov-b2
          text: |
            התחברו ועברו למסך החיפושים השמורים שלכם. לחצו על כל אחד מהם כדי מה השתנה לאחרונה
          action:
            text: למסך החיפושים השמורים
            target: href:/p/
        -
          title: איך ללמוד מניסיון של אחרים בממשלה?
          icon: gov-b3
          text: |
            חפשו התקשרויות קודמות על פי מילות מפתח רלוונטיות. תוכלו להעמיק בבדיקה בעזרת טבלת השאילתות המתקדמות בכל אחד מעמודי התוצאות.
          action:
            text: לחיפוש
            target: search
modals:
  procure_processes:
    title: קצת על תהליכי הרכש הממשלתיים
    text: |
          1. מי הם הגופים שרוכשים בשם הממשלה?
          <br/>
          2. מכרזים מרכזיים
          <br/>
          3. מכרזים משרדיים
          <br/>
          4. פטור ממכרז

  data_sources:
    title: מקורות המידע שלנו
    text: |
           1. המידע אודות הליכי הרכש - מכרזים ובקשות פטור ממכרז - נמשך מאתר מנהל רכש המרכזי.
           <br/>
           2. המידע על העברות הכספים במסגרת ההתקשרויות מפורסם במסגרת הדו"חות הרבעוניים של היחידות הממשלתיות. אנחנו מעבדים אותו ומחברים אותו עם נתוני תהליכי הרכש כך שאפשר יהיה להבין כמה מהכסף שאושר כבר שולם בכל נקודת זמן.

  actions_to_take:
    title: פעולות במסגרת הליכי רכש פעילים
    text: |
           1. מכרזים מרכזיים
           <br/>
           2. מכרזים משרדיים
           <br/>
           3. בקשות לפטור ממכרז
           <br/>

tooltips:
  central: |
    מכרז הנערך מטעם החשב הכללי באוצר עבור משרדי הממשלה השונים
  office: |
    מכרזים מטעמם של משרד או משרדים בודדים
  exemptions: |
    ישנם כ-30 מקרים בהם לפי החוק גופים ממשלתיים פטורים מעריכת מכרז
